###
# This parameter specifies the root url for the RestApi endpoints.
# Should not have a trailing "/"
API_ENDPOINT: "https://api.vhh-mmsi.eu/api/tbaservice"   # root url for API endpoints

###
# Path to the folder which will store the data
DATA_PATH: "/data/share/fjogl/vhh_rd_data"

###
# Path to the directory that contains the videos
VIDEO_PATH: "/data/ext/VHH/release_results/release_v1_3_0/vhh_core/videos_part1/"

###
# Path to the directory that contains the shot information
SHOT_PATH: "/data/ext/VHH/release_results/release_v1_3_0/vhh_core/results_part1/sbd/final_results"

###
# Model to use for feature extractor (resnet152, resnet50)
MODEL: "resnet50"

###
# Distance metric used to compute similarities (euclidean, manhattan, chebyshev, minkowski, seuclidean, mahalanobis)
DISTANCE_METRIC: "euclidean"

###
# Additional metric parameter, only used for minkowski
METRIC_PARAM: 20

###
# Batchsize 
BATCHSIZE: 16